---
swagger: "2.0"
info:
  description: e-Commerce application for XenElectronic
  title: XenElectronic
  version: 1.0.0
consumes:
  - application/xenelectronic.v1+json
produces:
  - application/xenelectronic.v1+json
schemes:
  - http
paths:
  /categories:
    get:
      description: List available categories
      tags:
        - categories
      operationId: listCategories
      responses:
        200:
          description: list the categories
          schema:
            type: array
            items:
              $ref: "#/definitions/Category"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
  /categories/{category_id}/products:
    get:
      description: List Products of a category
      tags:
        - categories
      operationId: listProductsOfCategory
      parameters:
        - name: category_id
          in: path
          required: true
          type: integer
          format: int64
        - name: since
          in: query
          type: integer
          format: int64
          default: 0
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list the products of selected category
          schema:
            type: array
            items:
              $ref: "#/definitions/Product"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
  /carts:
    post:
      description: Create new cart
      tags:
        - carts
      operationId: createCart
      responses:
        200:
          description: created new cart
          schema:
            type: object
            required:
              - cart_id
            properties:
              cart_id:
                type: string
                format: uuid
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
  /carts/{cart_id}/products:
    parameters:
      - name: cart_id
        in: path
        required: true
        type: string
        format: uuid
    get:
      description: List Products in the cart
      tags:
        - carts
      operationId: listProductsInCart
      responses:
        200:
          description: list the products in the cart
          schema:
            $ref: "#/definitions/CartItems"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
    post:
      description: Add a Product into cart
      tags:
        - carts
      operationId: addOneProductIntoCart
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - product_id
            properties:
              product_id:
                type: integer
                format: int64
      responses:
        200:
          description: add one product into the cart
          schema:
            $ref: "#/definitions/CartItem"
  /carts/{cart_id}/products/{product_id}:
    delete:
      description: Delete a Product from cart
      tags:
        - carts
      operationId: removeOneProductFromCart
      parameters:
        - name: cart_id
          in: path
          required: true
          type: string
          format: uuid
        - name: product_id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: product is deleted from cart
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"
  /orders:
    post:
      description: Create order for the cart
      tags:
        - orders
      operationId: checkout
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Order"
      responses:
        201:
          description: Created new order from cart
          schema:
            $ref: "#/definitions/ExtendedOrder"
        default:
          description: error
          schema:
            $ref: "#/definitions/Error"

definitions:
  Category:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
  Product:
    type: object
    required:
      - name
      - description
      - price
      - category_id
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      price:
        type: integer
        format: int64
      photo:
        type: string
      category_id:
        type: integer
        format: int64
  CartItem:
    type: object
    required:
      - product_id
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      product_id:
        type: integer
        format: int64
      product:
        readOnly: true
        $ref: "#/definitions/Product"
  CartItems:
    type: array
    items:
      $ref: "#/definitions/CartItem"
    example:
      - id: 1000
        product_id: 500
        product:
          category_id: 1
          id: 500
          name: Samsung LED TV
          description: Samsung LED TV
          price: 5000000
          photo: https://samsung.com
      - id: 1001
        product_id: 550
        product:
          category_id: 10
          id: 550
          name: Samsung Galaxy S20 Ultra
          description: Samsung Galaxy S20 Ultra
          price: 20000000
          photo: https://samsung.com
      - id: 1002
        product_id: 555
        product:
          category_id: 0
          id: 555
          name: iPhone 11 Pro
          description: iPhone 11 Pro
          price: 20000000
          photo: https://apple.com
  Order:
    type: object
    required:
      - cart_id
      - customer_name
      - customer_email
      - customer_address
    properties:
      id:
        type: string
        format: uuid
        readOnly: true
      cart_id:
        type: string
        format: uuid
      customer_name:
        type: string
        minLength: 1
      customer_email:
        type: string
        format: email
        minLength: 1
      customer_address:
        type: string
        minLength: 1
  ExtendedOrder:
    allOf:
      - $ref: "#/definitions/Order"
      - type: object
        properties:
          cart_items:
            $ref: "#/definitions/CartItems"
          payment_amount:
            type: integer
            format: int64
          payment_method:
            type: string
          payment_account_number:
            type: string
    example:
      id: aaaaaaaa-bbbb-cccc-dddd-eeeedeadbeef
      cart_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
      customer_name: John Doe
      customer_email: john@example.com
      customer_address: 1 Hacker Way
      payment_amount: 45000000
      payment_method: Bank Transfer
      payment_account_number: 232 555 8965
      cart_items:
        - id: 1000
          product_id: 500
          product:
            category_id: 1
            id: 500
            name: Samsung LED TV
            description: Samsung LED TV
            price: 5000000
            photo: https://samsung.com
        - id: 1001
          product_id: 550
          product:
            category_id: 10
            id: 550
            name: Samsung Galaxy S20 Ultra
            description: Samsung Galaxy S20 Ultra
            price: 20000000
            photo: https://samsung.com
        - id: 1002
          product_id: 555
          product:
            category_id: 0
            id: 555
            name: iPhone 11 Pro
            description: iPhone 11 Pro
            price: 20000000
            photo: https://apple.com
  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
